// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rehber.DataAccess;

namespace Rehber.DataAccess.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20220224161058_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rehber.Entities.Model.ContactInfo", b =>
                {
                    b.Property<int>("ContactInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfoContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoTypeID")
                        .HasColumnType("int");

                    b.Property<string>("PersonUID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ContactInfoID");

                    b.HasIndex("InfoTypeID")
                        .IsUnique();

                    b.HasIndex("PersonUID");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("Rehber.Entities.Model.InfoType", b =>
                {
                    b.Property<int>("InfoTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfoTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoTypeID");

                    b.ToTable("InfoTypes");
                });

            modelBuilder.Entity("Rehber.Entities.Model.Person", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Rehber.Entities.Model.ContactInfo", b =>
                {
                    b.HasOne("Rehber.Entities.Model.InfoType", "InfoType")
                        .WithOne("ContactInfo")
                        .HasForeignKey("Rehber.Entities.Model.ContactInfo", "InfoTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rehber.Entities.Model.Person", "Person")
                        .WithMany("ContactInfos")
                        .HasForeignKey("PersonUID");

                    b.Navigation("InfoType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Rehber.Entities.Model.InfoType", b =>
                {
                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("Rehber.Entities.Model.Person", b =>
                {
                    b.Navigation("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
